name: soc-anomaly-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - azureml-defaults
    - azure-ai-ml
    - azure-identity
    - scikit-learn
    - pandas
    - numpy
    - joblib
    - mlflow
    - azureml-mlflow
